database:
  host: 42.192.105.150
  port: 3306
  username: root
  password: 123456
  dbname: fuck_the_world_db_dev

email:
  host: smtp.qq.com
  port: 587
  username: 1446450047@qq.com
  password: rzmosrptpkatjgbc