basePath: '"/api/v1"'
host: 42.192.105.150:8888
info:
  contact:
    email: 1446450047@qq.com
    name: herzorf
    url: https://github.com/herzorf
  description: 接口文档
  termsOfService: https://github.com/herzorf
  title: 接口文档
  version: "1.0"
paths:
  /sendEmail:
    post:
      consumes:
      - application/json
      description: 发送验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: sendEmail
      tags:
      - sendEmail
swagger: "2.0"
