basePath: /
host: localhost:8080
info:
  contact:
    email: herzorf@icloud.com
    name: herzorf
    url: https://github.com/herzorf
  description: 这是一个简单的记账项目
  title: 项目文档
  version: "1.0"
paths:
  /ping:
    get:
      description: ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ping
      tags:
      - ping
swagger: "2.0"
